apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: company-ingress
  annotations:
    kubernetes.io/ingress.class: nginx  # Tells K8s to use NGINX Ingress Controller
spec:
  rules:
    - host: company.local
      http:
        paths:
          - path: /employee
            pathType: Prefix
            backend:
              service:
                name: employee-service # must match service name metadata.name
                port:
                  number: 8081  # must match the Serviceâ€™s port (Port filed), not the container port.
          - path: /department
            pathType: Prefix
            backend:
              service:
                name: department-service
                port:
                  number: 8082
